FROM centos:7
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN yum -y install centos-release-openstack-newton && yum -y install {{ packages | join (' ') }} && yum clean all

ADD     keystone.conf /etc/keystone
ADD     glance-registry.conf /etc/glance
ADD     glance-registry.conf /etc/glance
ADD     cinder.conf /etc/cinder
ADD     neutron.conf /etc/neutron
{% if neutron_core_plugin == 'ml2' %}
ADD     ml2_conf.ini /etc/neutron/plugins/ml2
{% endif %}
ADD     start.sh /usr/bin

RUN     chown root:root /usr/bin/start.sh && chmod u+x /usr/bin/start.sh

ENTRYPOINT  ["/usr/bin/start.sh"]
