FROM centos:7
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN yum -y install centos-release-openstack-newton && yum -y install {{ packages | join (' ') }} && yum clean all

ADD     keystonerc_admin /
ADD     keystonerc_admin_v3 /
ADD     neutron.conf /etc/neutron
ADD     dhcp_agent.ini /etc/neutron
ADD     dnsmasq-neutron.conf /etc/neutron
ADD     l3_agent.ini /etc/neutron
ADD     metadata_agent.ini /etc/neutron
{% if version == 'kilo' %}
ADD     plugin.ini /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
{% else %}
ADD     plugin.ini /etc/neutron/plugins/ml2/openvswitch_agent.ini
{% endif %}
ADD     ifcfg-br-int /etc/sysconfig/network-scripts
ADD     start.sh /usr/bin

RUN     chown root:root /usr/bin/start.sh && chmod u+x /usr/bin/start.sh

ENTRYPOINT  ["/usr/bin/start.sh"]
