FROM {{ openshaft.image }}
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN {{ pkgrelease }} yum -y install mariadb {{ packages | join (' ') }} && yum clean all

ADD     keystonerc_admin /
ADD     keystonerc_admin_v3 /
ADD     neutron.conf /etc/neutron
{% if neutron_core_plugin == 'ml2' %}
ADD     ml2_conf.ini /etc/neutron/plugins/ml2
{% endif %}
ADD     start.sh /usr/bin

RUN     chown root:root /usr/bin/start.sh && chmod u+x /usr/bin/start.sh

ENTRYPOINT  ["/usr/bin/start.sh"]
EXPOSE  9696
