# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias openshaft_mysql="docker run -d --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysql -d mysql:latest"
alias openshaft_rabbit="docker run -d --name rabbit -p 5672:5672 -d --hostname rabbit -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3-management"
alias openshaft_keystone="docker run -d --name keystone --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 5000:5000 -p 35357:35357 openshaft/keystone"
alias openshaft_glance="docker run -d --name glance --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 9191:9191 -p 9292:9292 -v /tmp/openshaft/glance_data:/var/lib/glance openshaft/glance"
alias openshaft_cinder="docker run -d --name cinder --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 8776:8776 openshaft/cinder"
alias openshaft_cinder-volume="docker run -d --name cinder-volume --privileged --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 --add-host nfs:172.17.0.1 openshaft/cinder-volume"
alias openshaft_neutron="docker run -d --name neutron --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 9696:9696 openshaft/neutron"
alias openshaft_neutron-agents1="docker run --privileged -d --name neutron-agents1 --hostname neutron-agents1 --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 openshaft/neutron-agents"
alias openshaft_neutron-agents2="docker run --privileged -d --name neutron-agents2 --hostname neutron-agents2--add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 openshaft/neutron-agents"
alias openshaft_nova="docker run -d --name nova --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 6080:6080 -p 8773:8773 -p 8774:8774 -p 8775:8775 openshaft/nova"
alias openshaft_clean="docker rm -f {glance,keystone,cinder,cinder-volume,nova,neutron,neutron-agents,rabbit,mysql}"
alias openshaft_restart="docker stop {keystone,glance,cinder,cinder-volume,neutron,neutron-agents,nova}; docker start {keystone,glance,cinder,cinder-volume,neutron,neutron-agents,nova}"
alias openshaft_heat="docker run -d --name heat --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 8000:8000 -p 8003:8003 -p 8004:8004 openshaft/heat"
alias openshaft_horizon="docker run -d --name horizon --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 -p 80:80 -p 443:443 openshaft/horizon"
alias openshaft_nova-compute="docker run -d --privileged --name nova-compute --add-host mysql:172.17.0.1 --add-host controller:172.17.0.1 --add-host rabbit:172.17.0.1 --add-host glance:172.17.0.1 --add-host cinder:172.17.0.1 --add-host neutron:172.17.0.1 --add-host nova:172.17.0.1 --add-host heat:172.17.0.1 --add-host ceilometer:172.17.0.1 --add-host nfs:172.17.0.1 -p 5900:5900 -p 5901:5901 -p 5902:5902 openshaft/nova-compute"
alias openshaft_swift="docker run -d --name swift --add-host controller:172.17.0.1 -p 8080:8080 openshaft/swift"
alias openshaft_swift-storage="docker run --privileged -v /dev/vdb:/dev/vdb -d --name swift-storage --add-host controller:172.17.0.1 -p 6200:6200 -p 6201:6201 -p 6202:6202 openshaft/swift-storage"

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
