FROM {{ openshaft.image }}
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN yum -y install centos-release-openstack-{{ common.version }} && yum -y install mariadb {{ packages | join (' ') }} && yum clean all

ADD     keystonerc_admin /
ADD     keystonerc_admin_v3 /
ADD     glance-api.conf /etc/glance
ADD     glance-registry.conf /etc/glance
ADD     start.sh /usr/bin

RUN     chown root:root /usr/bin/start.sh && chmod u+x /usr/bin/start.sh

ENTRYPOINT  ["/usr/bin/start.sh"]
EXPOSE  9191 9292
